ClothingWebApp/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClothingWebApp.Data;
using ClothingWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClothingWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext context;

        [BindProperty]
        public Category Category { get; set; }

        [TempData]
        public String Message { get; set; }

        public CategoryController(ApplicationDbContext context)
        {
            this.context = context;
        }

        //GET : CATEGORY
        public async Task<IActionResult> Index()
        {
            var returnCategory = await context.Categories.ToListAsync();
            return View(returnCategory);
        }

        //GET : CREATE
        public IActionResult Create()
        {
            Message = "Hello";
            return View();
        }

        [HttpPost, ActionName("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostCreate()
        {
            if (ModelState.IsValid)
            {
                context.Categories.Add(Category);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Category);
        }

        //GET : EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Category = await context.Categories.FindAsync(id);
            if (Category == null)
            {
                return NotFound();
            }
            return View(Category);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        //POST: EDIT
        public async Task<IActionResult> PostEdit(int? id)
        {
            if (ModelState.IsValid)
            {
                context.Categories.Update(Category);
                await context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(Category);
        }

        //GET : DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Category = await context.Categories.FindAsync(id);

            if (Category == null)
            {
                return NotFound();
            }
            return View(Category);
        }

        //GET DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Category = await context.Categories.FindAsync(id);
            if (Category == null)
            {
                return NotFound();
            }
            return View(Category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PostDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                context.Remove(Category);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Category);
        }
    }
}

ClothingWebApp/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClothingWebApp.Data;
using ClothingWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClothingWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext context;

        [BindProperty]
        public Coupon Coupon { get; set; }

        public CouponController(ApplicationDbContext context)
        {
            this.context = context;

        }
        public async Task<IActionResult> Index()
        {
            var returnFromDb = await context.coupons.ToListAsync();
            return View(returnFromDb);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostCreate(int? id)
        {
            if (ModelState.IsValid)
            {
                //Fletch the file
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    //files was uploaded

                    //Convert to stream of byte
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())//will start reading the file
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            //Convert into stream of byte and store into p1
                            p1 = ms1.ToArray();
                        }
                        Coupon.Picture = p1;
                    }
                }
                context.coupons.Add(Coupon);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(Coupon);
        }

        public async Task<IActionResult> Edit(int?id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Coupon = await context.coupons.FirstOrDefaultAsync(m => m.Id == id);
            if (Coupon == null)
            {
                return NotFound();
            }
            return View(Coupon);
        }

    }
}

ClothingWebApp/Areas/Admin/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClothingWebApp.Data;
using ClothingWebApp.Models;
using ClothingWebApp.Models.ViewModels;
using ClothingWebApp.Utility;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ClothingWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenuItemController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IHostingEnvironment hostingEnvironment;

        [BindProperty]
        public MenuItemViewModel MenuItemViewModel { get; set; }

        public MenuItemController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            this.context = context;
            this.hostingEnvironment = hostingEnvironment;
            MenuItemViewModel = new MenuItemViewModel()
            {
                MenuItem = new Models.MenuItem(),
                Categories = context.Categories
                //SubCategories = context.SubCategories,//This depends on which subcategories is selected 

            };
        }

        //GET INDEX
        public async Task<IActionResult> Index()
        {
            var attactchconxt = await context.MenuItems.Include(x => x.SubCategory).Include(x => x.Category).ToListAsync();

            if (attactchconxt == null)
            {
                return NotFound();
            }

            return View(attactchconxt);
        }

        //GET CREATE
        public IActionResult Create()
        {
            if (MenuItemViewModel == null)
            {
                return NotFound();
            }
            return View(MenuItemViewModel);
        }


        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostCreate()
        {
            //Assign Sub Category Post because it's been assigned using Javascript and no model has been passed
            MenuItemViewModel.MenuItem.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());

            if (!ModelState.IsValid)
            {
                return View(MenuItemViewModel);
            }

            context.MenuItems.Add(MenuItemViewModel.MenuItem);
            await context.SaveChangesAsync();

            //Work on the image saving section

            //Extra root Path and for that you need IHostingEnvironment
            string webRootPath = hostingEnvironment.WebRootPath;
            //Extract
            var files = HttpContext.Request.Form.Files;

            var MenuItemFromDb = await context.MenuItems.FindAsync(MenuItemViewModel.MenuItem.Id);
            if (files.Count > 0)
            {
                //Files has been upload
                var uploads = Path.Combine(webRootPath, "Images");
                var extension = Path.GetExtension(files[0].FileName);

                using (var filesStream = new FileStream(Path.Combine(uploads, MenuItemViewModel.MenuItem.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filesStream);
                }
                MenuItemFromDb.Image = @"\Images\" + MenuItemViewModel.MenuItem.Id + extension;
            }
            else
            {
                //No files was uploaded, so use default image
                var uploads = Path.Combine(webRootPath, @"Images\" + SD.DefaultFoodImage);
                System.IO.File.Copy(uploads, webRootPath + @"\Images\" + MenuItemViewModel.MenuItem.Id + ".png");
                MenuItemFromDb.Image = @"\Images\" + MenuItemViewModel.MenuItem.Id + ".png";

            }
            await context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        //GET - Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Retrieve the menu item
            MenuItemViewModel.MenuItem = await context.MenuItems
                .Include(x => x.Category)
                .Include(x => x.SubCategory)
                .SingleOrDefaultAsync(x => x.Id == id);
            //Load Sub Category
            MenuItemViewModel.SubCategories = await context.SubCategories
                .Where(s => s.CategoryId == MenuItemViewModel.MenuItem.CategoryId)
                .ToListAsync();
            if (MenuItemViewModel.MenuItem == null)
            {
                return NotFound();
            }
            return View(MenuItemViewModel);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //Assign Sub Category Post because it's been assigned using Javascript and no model has been passed
            MenuItemViewModel.MenuItem.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());

            if (!ModelState.IsValid)
            {
                //We populate before sending back
                MenuItemViewModel.SubCategories = await context.SubCategories
                    .Where(s => s.CategoryId == MenuItemViewModel.MenuItem.CategoryId).ToListAsync();
                return View(MenuItemViewModel);
            }

            //context.MenuItems.Add(MenuItemViewModel.MenuItem);
            //await context.SaveChangesAsync();

            //Work on the image saving section

            //Extra root Path and for that you need IHostingEnvironment
            string WebRootPath = hostingEnvironment.WebRootPath;
            //Extract
            var files = HttpContext.Request.Form.Files;

            var MenuItemFromDb = await context.MenuItems.FindAsync(MenuItemViewModel.MenuItem.Id);
            if (files.Count > 0)
            {
                //Files has been upload
                var uploads = Path.Combine(WebRootPath, "Images");
                var extension = Path.GetExtension(files[0].FileName);

                //Delete the original file therefore New file can be pasted
                var imagePath = Path.Combine(WebRootPath, MenuItemFromDb.Image.TrimStart('\\'));
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
                //We will upload a new file                
                using (var filesStream = new FileStream(Path.Combine(uploads, MenuItemViewModel.MenuItem.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filesStream);
                }
                MenuItemFromDb.Image = @"\Images\" + MenuItemViewModel.MenuItem.Id + extension;
            }

            //If image has not been upload we are going to do nothing


            MenuItemFromDb.Name = MenuItemViewModel.MenuItem.Name;
            MenuItemFromDb.Description = MenuItemViewModel.MenuItem.Description;
            MenuItemFromDb.Price = MenuItemViewModel.MenuItem.Price;
            MenuItemFromDb.ItemWeight = MenuItemViewModel.MenuItem.ItemWeight;
            MenuItemFromDb.CategoryId = MenuItemViewModel.MenuItem.CategoryId;
            MenuItemFromDb.SubCategoryId = MenuItemViewModel.MenuItem.SubCategoryId;

            await context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //GET - DETAILS

        public async Task<IActionResult> Details(int ? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Retrieve the menu item
            MenuItemViewModel.MenuItem = await context.MenuItems
                .Include(x => x.Category)
                .Include(x => x.SubCategory)
                .SingleOrDefaultAsync(x => x.Id == id);
            //Load Sub Category
            MenuItemViewModel.SubCategories = await context.SubCategories
                .Where(s => s.CategoryId == MenuItemViewModel.MenuItem.CategoryId)
                .ToListAsync();
            if (MenuItemViewModel.MenuItem == null)
            {
                return NotFound();
            }
            return View(MenuItemViewModel);
        }


        //GET - DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Retrieve the menu item
            MenuItemViewModel.MenuItem = await context.MenuItems
                .Include(x => x.Category)
                .Include(x => x.SubCategory)
                .SingleOrDefaultAsync(x => x.Id == id);
            //Load Sub Category
            MenuItemViewModel.SubCategories = await context.SubCategories
                .Where(s => s.CategoryId == MenuItemViewModel.MenuItem.CategoryId)
                .ToListAsync();
            if (MenuItemViewModel.MenuItem == null)
            {
                return NotFound();
            }
            return View(MenuItemViewModel);
        }


        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            string webRootPath = hostingEnvironment.WebRootPath;
            MenuItem menuItem = await context.MenuItems.FindAsync(id);
            if (menuItem != null)
            {
                var imagePath = Path.Combine(webRootPath, menuItem.Image.TrimStart('\\'));

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
                context.MenuItems.Remove(menuItem);
                await context.SaveChangesAsync();
            }

ClothingWebApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClothingWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />


    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <!-- Navbar -->
        <div id="#topheader" class="w3-top">
            <div class="w3-bar w3-red w3-card w3-left-align w3-large">
                <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu">
                    <i class="fa fa-bars"></i>
                </a>
                <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
                @*<a href="#" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>*@
                @*<a asp-area="Customer" asp-controller="Home" asp-action="Privacy" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Privacy </a>*@
                <a asp-area="Admin" asp-controller="MenuItem" asp-action="Index" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Admin</a>
                <partial name="_LoginPartial" />
            </div>
            <!-- Navbar on small screens -->
            <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
                <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-padding-large">Home</a>
                @*<a asp- area="Customer" asp-controller="Home" asp-action="Privacy" class="w3-bar-item w3-button w3-padding-large">Privacy</a>*@
            </div>
        </div>
    </header>
    <br />

    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            <!-- Top container -->
            <div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
                <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
            </div>
            <!-- Sidebar/menu -->
            <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar">
                <br>
                <div class="w3-container w3-row">
                    <div class="w3-col s4">
                        <img src="~/Images/Mike.png" class="w3-circle w3-margin-right" style="width:46px">
                    </div>
                    <div class="w3-col s8 w3-bar">
                        <span>Welcome, <strong>Mike</strong></span><br>
                        <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
                        <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
                        <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
                    </div>
                </div>
                <hr>
                <div class="w3-container">
                    <h5>Dashboard</h5>
                </div>
                <div class="w3-bar-block">
                    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i> Close Menu</a>

                    <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="w3-bar-item w3-button w3-padding"><i class="fas fa-border-all"></i>&nbsp;&nbsp;Category</a>
                    <a asp-area="Admin" asp-controller="SubCategory" asp-action="Index" class="w3-bar-item w3-button w3-padding"><i class="fas fa-industry"></i>&nbsp;&nbsp;Make</a>
                    <a asp-area="Admin" asp-controller="MenuItem" asp-action="Index" class="w3-bar-item w3-button w3-padding"><i class="fas fa-store"></i>&nbsp;&nbsp;Item Database</a>
                    <a asp-area="Admin" asp-controller="Coupon" asp-action="Index" class="w3-bar-item w3-button w3-padding"><i class="fas fa-calendar-alt"></i>&nbsp;&nbsp;Events</a>
                </div>
            </nav>
            <!-- Overlay effect when opening sidebar on small screens -->
            <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

            <!-- !PAGE CONTENT! -->
            <div class="w3-main" style="margin-left:300px;margin-top:43px;">

                <!-- Header -->
                @*<header class="w3-container" style="padding-top:22px">
                        <h5><b><i class="fa fa-dashboard"></i> My Dashboard</b></h5>
                    </header>*@
                <!--Contain goes here-->
                @RenderBody()
                <!-- End page content -->
            </div>
        </main>
    </div>

    <div class="container">
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - ClothingWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>



    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/a1b3c5cc28.js"></script>
    <script>
        // Used to toggle the menu on small screens when clicking on the menu button
        function myFunction() {
            var x = document.getElementById("navDemo");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }
        // Get the Sidebar
        var mySidebar = document.getElementById("mySidebar");

        // Get the DIV with overlay effect
        var overlayBg = document.getElementById("myOverlay");

        // Toggle between showing and hiding the sidebar, and add overlay effect
        function w3_open() {
            if (mySidebar.style.display === 'block') {
                mySidebar.style.display = 'none';
                overlayBg.style.display = "none";
            } else {
                mySidebar.style.display = 'block';
                overlayBg.style.display = "block";
            }
        }

        // Close the sidebar with the close button
        function w3_close() {
            mySidebar.style.display = "none";
            overlayBg.style.display = "none";
        }

    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ClothingWebApp/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>

    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ClothingWebApp/Views/Shared/_CreateTableButtonPartial.cshtml
<a asp-action="Create" class="btn btn-primary text-white"><i class="fas fa-user-plus"></i></a>

ClothingWebApp/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" value="Delete" asp-route-id="@Model" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ClothingWebApp/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a asp-action="Edit" class="btn btn-info form-control" asp-route-id="@Model">Move to Edit</a>
    </div>

    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ClothingWebApp/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Edit" asp-route-id="@Model" />
    </div>

    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ClothingWebApp/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

ClothingWebApp/Views/Shared/_TableButtonPartial.cshtml
@model int


<a class="btn btn-secondary text-white" asp-action="Edit" asp-route-Id="@Model">
    <i class="fas fa-user-edit"></i>
</a>
<a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
    <i class="fas fa-address-card"></i>
</a>
<a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
    <i class="fas fa-user-times"></i>
</a>

ClothingWebApp/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>


@if (Model.Count() > 0)
{
    <div class="col-12">
        <div class="row">
            <h3 class="text-success">
                @Model.FirstOrDefault().Category.Name
            </h3>
        </div>
        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px; border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon">@item.Name</label>
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>£@item.Price</h4>
                            </div>
                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9">
                            <a asp-action="Details" class="btn btn-primary form-control" asp-route-id="@item.Id">Add to Basket</a>
                        </div>

                    </div>
                </div>
            </div>
        }


    </div>
}